django_faqs/urls.py
from django.conf.urls.defaults import *
from views import IndexView

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view()),
)

django_faqs/models.py
from django.db import models

class Section(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return u'%s' % (self.name)


class Question(models.Model):
    section = models.ForeignKey(Section)
    question = models.CharField(max_length=200)
    answer = models.TextField()

django_faqs/views.py
from django.views.generic import TemplateView
from models import Section, Question
import string

class IndexView(TemplateView):
    template_name = 'faqs/index.html'

    def get_context_data(self, **kwargs):
        return {'sections': Section.objects.all()}

    def render_to_response(self, context, **response_kwargs):
        if 'app_config' in getattr(self.request, '_feincms_extra_context', {}):
            return self.get_template_names(), context

        return super(IndexView, self).render_to_response(context, **response_kwargs)

django_faqs/templates/faqs/base.html
{% extends feincms_page.template.path|default:"base.html" %}

django_faqs/templates/faqs/index.html
{% extends "faqs/base.html" %}
{% load sekizai_tags %}

{% block content %}
	{% addtoblock 'js' %}
		<script src="{{STATIC_URL}}js-lib/jquery.dl_show_hide.js" type="text/javascript" charset="utf-8"></script>
	{% endaddtoblock %}

	<div class="row">
		{% for section in sections %}
			<div class="span6">
				<h2>{{section.name}}</h2>
				<hr>
				<dl class="dl-show-hide">
				{% for question in section.question_set.all %}
					<dt><i class="icon-circle-arrow-right"></i> {{question.question}}</dt>
						<dd>{{question.answer}}</dd>
					<hr>
				{% endfor %}
				</dl>
			</div>
		{% endfor %}
	</div>
{% endblock content %}